services:
  - type: web
    name: wbaatz-notes-backend
    env: node
    plan: free
    buildCommand: npm install -g pnpm@latest && pnpm install --frozen-lockfile && pnpm --filter api-server build
    startCommand: cd api-server && pnpm start
